# NumPy Arrays

In [1]:
import numpy as np

In [2]:
#creating NumPy 1D Array..
arr_1d = np.array([1,2,3,4])
print(arr_1d)   

[1 2 3 4]


In [4]:
type(arr_1d) #checking if it is a NumPy Array or not...

numpy.ndarray

In [5]:
arr_1d.ndim  #array_name.ndim is used to find the dimensions of an NumPy array...

1

In [7]:
#creating NumPy 2D Array..
arr_2d = np.array([[1,2,3,4], [5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
arr_2d.ndim

2

In [10]:
arr_1d.size  #array_name.size is used to find the size(total no. of elements) of the Array...

4

In [11]:
arr_2d.size

8

In [12]:
arr_2d.shape  #array_name.shape is used to find the shape(no. of row and columns) of the Array... OUTPUT-> (row, colm)

(2, 4)

In [13]:
arr_2d.dtype #array_name.dtype  is used to find which DataType the NumPy Array contains...

dtype('int32')

In [14]:
#creating 1D matrix of element 1 only..
mx_1s = np.ones(5)
print(mx_1s)        

[1. 1. 1. 1. 1.]


In [15]:
mx_1s.dtype  #default datatype of the np.ones(shape) is floating point number...

dtype('float64')

In [18]:
#creating 2D matrix of specific shape and size..
mx_1s_2d = np.ones((3,4))
print(mx_1s_2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
#creating 2D matrix of specific shape and specific DataType...
mx_1s_2d = np.ones((3,4), dtype = int)
print(mx_1s_2d)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [20]:
#creating matrix of element zero only...
mx_0s = np.zeros((4,6))
print(mx_0s)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [21]:
#creating a zero matrix of specific datatype..
mx_0s = np.zeros((4,6), dtype = bool)
print(mx_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [22]:
mx_0s = np.zeros((4,6), dtype = str)
print(mx_0s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [23]:
#creating empty Array of specific size..
mx_empty = np.empty((3,3))
print(mx_empty)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 6.79834329e-321]
 [1.37959740e-306 2.29175545e-312 0.00000000e+000]]
