# Important NumPy Functions

In [2]:
import numpy as np

## arange()

In [13]:
#creating 1D array in a specific range with a specific steps..
arr_1d = np.arange(1, 13)
arr_1d2 = np.arange(0, 18)
arr_1d3 = np.arange(1, 13, 2)
arr_1d4 = np.arange(0, 13, 3)
print(arr_1d)
print(arr_1d2)
print(arr_1d3)
print(arr_1d4)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[ 1  3  5  7  9 11]
[ 0  3  6  9 12]


## linspace()

In [12]:
#creating 1D array of p numbers(with a same gap) between n and m...
np.linspace(1, 5, 6)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

## reshape()

In [21]:
print("The 1D Array was ->")
print(arr_1d)

#changing the 1D Array to 2D Array..
arr_2d = arr_1d.reshape(2, 6)
print("\nConversion of 1D Array to 2D Array ->")
print(arr_2d)

#changing the shape of an 2D Array..
arr_2d = arr_2d.reshape(3, 4)
print("\nAfter Changing The Shape of 2D Array, Array Becomes ->")
print(arr_2d)

#changing the 1D Array to 3D Array..
arr_3d = arr_2d.reshape(2, 3, 2)
print("\nConversion of 1D Array to 3D Array ->")
print(arr_3d)

#changing the shape of a 3D Array..
arr_3d = arr_3d.reshape(3, 2, 2)
print("\nAfter Changing The Shape of 3D Array, Array Becomes ->")
print(arr_3d)

The 1D Array was ->
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Conversion of 1D Array to 2D Array ->
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

After Changing The Shape of 2D Array, Array Becomes ->
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Conversion of 1D Array to 3D Array ->
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

After Changing The Shape of 3D Array, Array Becomes ->
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [23]:
arr = np.arange(6,18).reshape(3,4)
print(arr)

[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]


## ravel()

In [33]:
arr_1d = arr.ravel() #default order is 'C' i.e. row-major order..
print("2D Array to 1D Array ->")
print(arr_1d)

arr_1d = arr_3d.ravel('F') #order is here 'F' i.e. column-major order..
print("\n3D Array to 1D Array ->")
print(arr_1d)

2D Array to 1D Array ->
[ 6  7  8  9 10 11 12 13 14 15 16 17]

3D Array to 1D Array ->
[ 1  5  9  3  7 11  2  6 10  4  8 12]


## flatten()

In [35]:
arr.flatten('F')  #'F' means column-major order..

array([ 6, 10, 14,  7, 11, 15,  8, 12, 16,  9, 13, 17])

## transpose()

In [43]:
print("The Array(3x4) is ->")
print(arr)

print("\nTranspose of the array is ->")
print(arr.transpose())

The Array(3x4) is ->
[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]

Transpose of the array is ->
[[ 6 10 14]
 [ 7 11 15]
 [ 8 12 16]
 [ 9 13 17]]


In [49]:
# we can use "array_name.T" to transpose a matrix...
arr_2d = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
print(arr_2d)

print("\nTranspose of the above matrix is ->")
print(arr_2d.T)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Transpose of the above matrix is ->
[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]
