# MATHEMATIC OPERATIONS USING NUMPY

In [1]:
import numpy as np

In [9]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(2,20,2).reshape(3,3)

print("1st array is ->")
print(arr1)
print("\n2nd array is ->")
print(arr2)

1st array is ->
[[1 2 3]
 [4 5 6]
 [7 8 9]]

2nd array is ->
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## Addition of Two Matrix

In [10]:
arr1 + arr2

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [35]:
result_arr = np.add(arr1, arr2)
print(result_arr)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


## Subtraction

In [12]:
arr2 - arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
result_arr = np.subtract(arr2, arr1)
print(result_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Division

In [17]:
arr2 / arr1

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [19]:
result_arr = np.divide(arr2, arr1)
print(result_arr)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


## Multiplication of Respective Elements of Two Arrays..

In [20]:
arr1 * arr2

array([[  2,   8,  18],
       [ 32,  50,  72],
       [ 98, 128, 162]])

In [21]:
result_arr = np.multiply(arr1, arr2)
print(result_arr)

[[  2   8  18]
 [ 32  50  72]
 [ 98 128 162]]


## Matrix Multiplication (Dot Product)

In [22]:
arr1 @ arr2

array([[ 60,  72,  84],
       [132, 162, 192],
       [204, 252, 300]])

In [23]:
result_arr = arr1.dot(arr2)
print(result_arr)

[[ 60  72  84]
 [132 162 192]
 [204 252 300]]


## Finding Maximum/Minimum Element

In [26]:
arr1.max()  #to find the maximum element in an Array..

9

In [27]:
arr1.argmax()  #to find the index of the maximum element in an Array..

8

In [29]:
# finding the maximum element in each column
arr1.max(axis = 0)   #"axis = 0" means Column...

array([7, 8, 9])

In [30]:
# finding the maximum element in each row
arr1.max(axis = 1)   #"axis = 0" means Row...

array([3, 6, 9])

In [31]:
arr1.min()  #to find the minimum element in an Array..

1

In [32]:
arr1.argmin()  #to find the index of the minimum element in an Array..

0

In [33]:
# finding the minimum element in each column
arr1.min(axis = 0)     #"axis = 0" means Column...

array([1, 2, 3])

In [34]:
# finding the minimum element in each row
arr1.min(axis = 1)    #"axis = 1" means Row...

array([1, 4, 7])

## sum() Function

In [36]:
# finding sum of all elements in a matrix
np.sum(arr1)

45

In [40]:
# finding the sum of elements in each Column...
np.sum(arr1, axis = 0)

array([12, 15, 18])

In [41]:
# finding the sum of elements in each Row...
np.sum(arr1, axis = 1)

array([ 6, 15, 24])

## ** Other Important Operations

In [42]:
# Finding the Mean of All Elements in an Array..
np.mean(arr2)

10.0

In [43]:
# Finding the Square Root of Each elements in an Array..
np.sqrt(arr2)

array([[1.41421356, 2.        , 2.44948974],
       [2.82842712, 3.16227766, 3.46410162],
       [3.74165739, 4.        , 4.24264069]])

In [44]:
# Finding the Standard Deviation of All Elements in an Array..
np.std(arr2)

5.163977794943222

In [45]:
# Finding the Exponent of Each elements in an Array..
np.exp(arr2)

array([[7.38905610e+00, 5.45981500e+01, 4.03428793e+02],
       [2.98095799e+03, 2.20264658e+04, 1.62754791e+05],
       [1.20260428e+06, 8.88611052e+06, 6.56599691e+07]])

In [46]:
# Finding the log of Each elements in an Array..
np.log(arr2)

array([[0.69314718, 1.38629436, 1.79175947],
       [2.07944154, 2.30258509, 2.48490665],
       [2.63905733, 2.77258872, 2.89037176]])