# NumPy Array Slicing

In [2]:
import numpy as np

In [3]:
mx = np.arange(1,101).reshape(10,10)
print(mx)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


### Accessing Elements with its Index

In [4]:
mx[0,0]   # SYNTAX : matrix_name[row, colm]

1

In [5]:
mx[3,2]

33

In [6]:
mx[0,0].ndim  #this will return 0, as the dimension of a number is zero..

0

### Accessing Rows

In [7]:
mx[0]   # SYNTAX : matrix_name[row]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
mx[4]

array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [9]:
mx[0].ndim  #this will return 1, as this is an 1D Array sliced from a Big 2D Array...

1

In [10]:
# Accessing Row Elements in a Two-Dimensional Matrix..
mx[0:1,]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [11]:
#check the dimension and it will be 2..
mx[0:1,].ndim

2

### Accessing Columns

In [12]:
mx[:, 0]  # SYNTAX : matrix_name[:, column]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [13]:
mx[:, 5]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [14]:
mx[:, 3].ndim #return 1, as this is an 1D Array sliced from an Big 2D Array...

1

In [15]:
# Accessing Column Elements in a Two-Dimensional Matrix..
mx[:, 0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [16]:
# check the dimension and it will be 2..
mx[:, 0:1].ndim

2

### Slicing A Big Matrix
#### _SYNTAX_ : matrix_name[ (row_n : row_m),  (col_n : col_m)]
######                                          ```Note :  row_m   and   col_m    are excluded here```

In [17]:
# Slicing n_th Row to m_th Row of a Matrix..

print("First Two Row -> ")
print(mx[0:2,])

print("\nThird to Sixth Row -> ")
print(mx[2:6,])

First Two Row -> 
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]

Third to Sixth Row -> 
[[21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [18]:
# Slicing n_th Column to m_th Column of a Matrix..

print("First Three Column ->")
print(mx[:, 0:3])

print("\nLast Four Column -> ")
print(mx[:, 6:10])

First Three Column ->
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]
 [51 52 53]
 [61 62 63]
 [71 72 73]
 [81 82 83]
 [91 92 93]]

Last Four Column -> 
[[  7   8   9  10]
 [ 17  18  19  20]
 [ 27  28  29  30]
 [ 37  38  39  40]
 [ 47  48  49  50]
 [ 57  58  59  60]
 [ 67  68  69  70]
 [ 77  78  79  80]
 [ 87  88  89  90]
 [ 97  98  99 100]]


In [19]:
# Slicing n_th to m_th Row and p_th to q_th Column of a Matrix..

print("3rd to 7th Row x 4th to 6th column : ")
print(mx[2:7, 3:6])

3rd to 7th Row x 4th to 6th column : 
[[24 25 26]
 [34 35 36]
 [44 45 46]
 [54 55 56]
 [64 65 66]]


In [20]:
# finding the memory consumed by each element of a matrix...
mx.itemsize

4

In [21]:
# finding the datatype, matrix/2D array is stored in it..
mx.dtype

dtype('int32')