# Array Concatination and Split

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [3]:
arr2 = np.arange(17,33).reshape(4,4)
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


## np.concatenate()
### ``` SYNTAX : np.concatenate((array_1, array_2), axis = 0/1)  [ 0 -> Column(default) ; 1 -> Row ]```

In [4]:
# Concatenating Two Arrays Columnwise..

np.concatenate((arr1, arr2))  #"np.concatenate((arr1, arr2), axis = 0)" can also be written..


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [6]:
# Concatenating Two Arrays Row-wise...

np.concatenate((arr1, arr2), axis = 1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

## np.vstack()

In [7]:
# Array concatenation vertically..

np.vstack((arr1, arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [8]:
# Array concatenation vertically..

np.vstack((arr1, arr2, arr1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## np.hstack()

In [10]:
# Array concatenation Horizontally..

np.hstack((arr1, arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [11]:
# Array concatenation Horizontally..

np.hstack((arr1, arr2, arr1))

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

## np.split()
### ```Splits a List into Parts.. and Returns a List of Array...```

In [19]:
# Split Array into Two Equal Parts Column-Wise..
print(np.split(arr1, 2))

# Split Array into Four Equal Parts Column-Wise..
print(np.split(arr1, 4))

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])]


In [13]:
type(np.split(arr1, 2))

list

In [20]:
# Split Array into Two Equal Parts Row-Wise..
print(np.split(arr1, 2, axis = 1))

# Split Array into Four Equal Parts Row-Wise..
print(np.split(arr1, 4, axis = 1))

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]
[array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]]), array([[ 4],
       [ 8],
       [12],
       [16]])]


In [28]:
d1 = np.array([4,7,1,3,9,5,7,2,6])

In [29]:
# Spliting 1st element and then upto 3rd element.. 

np.split(d1, [1,3])

[array([4]), array([7, 1]), array([3, 9, 5, 7, 2, 6])]

In [30]:
# Spliting first upto 2nd elements and then upto 5th element..

np.split(d1, [2,5])

[array([4, 7]), array([1, 3, 9]), array([5, 7, 2, 6])]

In [31]:
# Spliting first upto 2nd elements and then upto 5th element and then upto 7th element..

np.split(d1, [2,5,7])

[array([4, 7]), array([1, 3, 9]), array([5, 7]), array([2, 6])]