# Random Sampling with Numpy

In [2]:
import numpy as np

### random.random()  function
#### ```SYNTAX : np.random.random(height, row, column)```

In [2]:
# "np.random.random()" generates a random value b/w 0 and 1, and returns an array.
np.random.random(1)

array([0.77038081])

In [5]:
# Generating array of specific shape, containing random number b/w 0 and 1.
np.random.random((5,4))

array([[0.40949294, 0.66889481, 0.42219388, 0.31504419],
       [0.08273361, 0.3294771 , 0.2159286 , 0.63611172],
       [0.37642317, 0.12278597, 0.52259978, 0.60604597],
       [0.94883868, 0.53564713, 0.13814225, 0.47249089],
       [0.0926377 , 0.35396912, 0.34111232, 0.41382585]])

In [7]:
np.random.random((3,3,3))

array([[[6.72067089e-01, 4.50922105e-01, 4.84144289e-01],
        [4.32712460e-01, 2.45750631e-01, 3.95043798e-01],
        [9.42273544e-01, 1.27130847e-01, 1.79130706e-01]],

       [[3.83113976e-01, 7.31212934e-01, 6.47468350e-01],
        [3.71613516e-01, 7.91120640e-01, 3.43638191e-01],
        [8.01958618e-01, 4.47583490e-01, 6.86586073e-04]],

       [[2.67176907e-01, 6.04664094e-01, 1.11742062e-01],
        [4.48945572e-03, 3.37170417e-02, 5.58621860e-01],
        [9.26556368e-01, 4.29920963e-01, 5.60457634e-01]]])

### random.randint()  function
#### ```Generates Random Integer Number b/w two integers```
#### ``` SYNTAX : random.randint(start, end, (height, row, column))```

In [8]:
np.random.randint(1,5)

3

In [9]:
np.random.randint(1,5)

3

In [11]:
#Generating 20 Random numbers b/w 1 to 10
for a in range(20):
    print(np.random.randint(1,10))

2
5
8
2
5
9
1
5
4
2
3
9
2
7
4
5
3
6
8
9


In [12]:
#Generating Matrix of specific shape, containing Random Numbers b/w 1 to 4.
np.random.randint(1,4, (4,4))

array([[2, 2, 3, 3],
       [2, 1, 2, 2],
       [3, 1, 2, 2],
       [3, 2, 2, 1]])

In [13]:
np.random.randint(1,4, (3,3,3))

array([[[3, 1, 3],
        [1, 1, 1],
        [1, 1, 3]],

       [[2, 1, 2],
        [3, 3, 2],
        [3, 3, 1]],

       [[1, 1, 2],
        [3, 1, 1],
        [2, 3, 1]]])

### rand() and randn()  function

In [14]:
# Generating Array of specific size containing random number b/w 0 and 1
np.random.rand(3)

array([0.14083403, 0.8763305 , 0.79521941])

In [15]:
np.random.rand(3,3)

array([[0.76526672, 0.82844714, 0.73001762],
       [0.6526597 , 0.4919978 , 0.744781  ],
       [0.81793958, 0.34217087, 0.48135163]])

In [4]:
# Generating Array of Random negative and Positive numbers..
np.random.randn(3,3)

array([[ 0.59069632,  0.2658484 , -1.26468239],
       [ 0.63582432,  0.07691859, -1.31851021],
       [-0.01021922, -0.67706717,  0.38136249]])

### choice()  function

In [18]:
x = [1,2,3,4,5,6]   #List of six numbers...

#Choosing a random no. from the list
np.random.choice(x)

2

In [19]:
np.random.choice(x)

6

In [21]:
for i in range(5):
    print(np.random.choice(x))

3
4
1
1
4


### permutation()  function

In [22]:
#Permutation of the list x = [1,2,3,4,5,6]

np.random.permutation(x)

array([1, 4, 5, 3, 6, 2])

In [23]:
np.random.permutation(x)

array([2, 6, 3, 1, 5, 4])

In [27]:
#Shuffles the Items of a List..
np.random.shuffle(x)
print(x)                #Items of the list now has been changed

[6, 5, 3, 4, 1, 2]
